import './js/dark-theme';
import './js/modal';
// import './js/header';
import './js/date';
import './js/guess';
import './js/rsp';
import './js/calculator';
import './js/time-calculator';
// import './js/dinosaur';
import './js/football';
import './js/enter-numbers';
import './js/our-team';
import './js/scientists';